### ISSUE TITLE
knight model

### ISSUE THREAD

**Issue by johnroper100** [johnroper100/STORY#23]
Finished

**Comment by Ahenryb** [comment]
Do the knights need a sword?

**Comment by johnroper100** [comment]
Yes. But some also have bows. So about half and half.

On Thursday, June 11, 2015, Ahenryb notifications@github.com wrote:

> Do the knights need a sword?
> 
> —
> Reply to this email directly or view it on GitHub.<
> https://ci5.googleusercontent.com/proxy/O0O9w6aRlzGfjqkrDLZW3o6XyML08Sw31BIv3AFAhvJxk5rTpLenDyx2C8NdIztmy9E-5ca80ZSk__st-ygzcCjqK2ZdT1UbuCpPlYm-7k7inW9Vo6SefJVhv3Jqjy398MdTvNtprtGICbUCpBsELev8hnVnRA=s0-d-e1-ft#https://github.com/notifications/beacon/AJVGn23Q1Jdo068h4E3Szz0aWwfMrc33ks5oSP-jgaJpZM4EvmWk.gif

## 

John roper
President and CEO of Starlight Graphics Studio
Boston, MA USA
http://starlightgraphics.co.nf/

**Comment by Ahenryb** [comment]
May some modelers get working on the knight's and king's props, please.

**Comment by johnroper100** [comment]
ok

On Thu, Jun 11, 2015 at 8:02 AM, Ahenryb notifications@github.com wrote:

> May some modelers get working on the knight's and king's props, please.
> 
> > On Jun 11, 2015, at 4:46 AM, John Roper notifications@github.com
> > wrote:
> > 
> > Yes. But some also have bows. So about half and half.
> > 
> > On Thursday, June 11, 2015, Ahenryb notifications@github.com wrote:
> > 
> > > Do the knights need a sword?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.<
> > 
> > https://ci5.googleusercontent.com/proxy/O0O9w6aRlzGfjqkrDLZW3o6XyML08Sw31BIv3AFAhvJxk5rTpLenDyx2C8NdIztmy9E-5ca80ZSk__st-ygzcCjqK2ZdT1UbuCpPlYm-7k7inW9Vo6SefJVhv3Jqjy398MdTvNtprtGICbUCpBsELev8hnVnRA=s0-d-e1-ft#https://github.com/notifications/beacon/AJVGn23Q1Jdo068h4E3Szz0aWwfMrc33ks5oSP-jgaJpZM4EvmWk.gif
> > 
> > 
> > ## 
> > 
> > John roper
> > President and CEO of Starlight Graphics Studio
> > Boston, MA USA
> > http://starlightgraphics.co.nf/
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/starlightgraphics/STORY/issues/23#issuecomment-111106922
> .

## 

John roper
President and CEO of Starlight Graphics Studio
Boston, MA USA
http://starlightgraphics.co.nf/
