### ISSUE TITLE
king model

### ISSUE THREAD

**Issue by johnroper100** [johnroper100/STORY#29]
Use the concept art provided by Pheonix

**Comment by Ahenryb** [comment]
do we need a staff or a scepter for the king?

**Comment by johnroper100** [comment]
Scepter.

On Thursday, June 11, 2015, Ahenryb notifications@github.com wrote:

> do we need a staff or a scepter for the king?
> 
> —
> Reply to this email directly or view it on GitHub.<
> https://ci4.googleusercontent.com/proxy/_xZlksXJoj9U4Uo30lE1esVcV0xjV9siYwaidCl3XBgWcb7GajZ-xLnshsXeby_4wIZjZO1UQg3JNCze1-b0w6n-bmxqvlW0ciL4OPy0Y7Cmy1wiA_hy8LyqJ3gro4ZsWwyWzfTzF2BNAHoLUjD-Yq8ceH_iDQ=s0-d-e1-ft#https://github.com/notifications/beacon/AJVGn6J6n1y_K2C6NNjyYB9t2q_RmAzhks5oSP98gaJpZM4EvpkE.gif

## 

John roper
President and CEO of Starlight Graphics Studio
Boston, MA USA
http://starlightgraphics.co.nf/
