### ISSUE TITLE
dragon rig

### ISSUE THREAD

**Issue by johnroper100** [johnroper100/STORY#34]
What should we do about the wings? I was thinking that you could rig the skin in beetween like you did with the princess' dress.

**Comment by Ahenryb** [comment]
Yep, I will do that to the skin folds to my best ability that it will look natural.

**Comment by Ahenryb** [comment]
Who should be in charge if the first scene for animation.

**Comment by johnroper100** [comment]
I will do camera, and I will setup the same system that we have for models
for animation.

On Saturday, June 6, 2015, Ahenryb notifications@github.com wrote:

> Who should be in charge if the first scene for animation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/starlightgraphics/STORY/issues/34#issuecomment-109654079
> .

## 

John roper
President and CEO of Starlight Graphics Studio
Boston, MA USA
http://starlightgraphics.co.nf/
