### ISSUE TITLE
castle tower

### ISSUE THREAD

**Issue by johnroper100** [johnroper100/STORY#40]

**Comment by ghost** [comment]
does this include the interior spaces for the dragon raid?

**Comment by johnroper100** [comment]
you are looking from above at the tower

On Mon, Jun 22, 2015 at 10:59 AM, GallantShow notifications@github.com
wrote:

> does this include the interior spaces for the dragon raid?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/starlightgraphics/STORY/issues/40#issuecomment-114141419
> .

## 

John roper
President and CEO of Starlight Graphics Studio
Boston, MA USA
http://starlightgraphics.tuxfamily.org

**Comment by ghost** [comment]
scene 4, shot 3
