### ISSUE TITLE
cave gold

### ISSUE THREAD

**Issue by johnroper100** [johnroper100/STORY#48]

**Comment by Ahenryb** [comment]
For the gold, does it need to be in ore form or gold bars?

**Comment by johnroper100** [comment]
I was thinking that it should be like rocks of different sizes and (sort
of) shapes.

On Sun, Jun 21, 2015 at 1:06 PM, Ahenryb notifications@github.com wrote:

> For the gold, does it need to be in ore form or gold bars?
> 
> > On Jun 21, 2015, at 10:49 AM, John Roper notifications@github.com
> > wrote:
> > 
> > Assigned #48 to @Ahenryb.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/starlightgraphics/STORY/issues/48#issuecomment-113930836
> .

## 

John roper
President and CEO of Starlight Graphics Studio
Boston, MA USA
http://starlightgraphics.tuxfamily.org
